apiVersion: apps/v1

kind: Deployment

metadata:
  name: flask-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: flask-app

  template:
    metadata:
      labels:
        app: flask-app

    spec:
      containers:
        - name: flask-app

          image: miroslavaskl126/flask-app:73a3e591ba7789261e8ae55e9076d11066637988

          imagePullPolicy: Always

          ports:
            - containerPort: 5000
          
          env:
            - name: VERSION 
              value: "73a3e591ba7789261e8ae55e9076d11066637988"